Numpy 是一个优秀的科学计算库，提供了很多实用的数学函数、强大的多维数组对象和优异的计算性能。

Numpy 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，以及大量的数学函数库。NumPy 的核心是 ndarray 对象，它是一个功能强大的 N 维数组对象，封装了 N 维同类数组。

很多运算是由编译过的代码来执行的，以此来提高效率。

Numpy 的主要对象是同种元素的多维数组。

这是一个所有元素都是一种类型、通过一个正整数元组索引的元素表格(通常是元素是数字)。在 Numpy 中维度(dimensions)叫做轴(axes)，轴的个数叫做秩(rank)

## 创建数组

array 本身的属性: 
+ `shape`: 返回一个元组，表示 array 的维度
+ `ndim`: 一个数字，表示 array 的维度的数目
+ `size`: 一个数字，表示 array 中所有数据元素的数目
+ `dttype`: array 中元素的数据类型


### 一维数组

In [16]:
import numpy as np
data = np.array([1,2,3,4])
print(data)

[1 2 3 4]


### 二维数组

In [26]:
import numpy as np
data = np.array([
    [1,2,3,4],
    [4,5,6,7]
])
print(data)

[[1 2 3 4]
 [4 5 6 7]]


### 创建全0、1、空数组

`shape` 属性代表形状
 
`shape(2，5)` 就代表创建2行5列的全零数组

In [18]:
# 全0数组
import numpy as np
data_1 = np.zeros(shape=(5,3))
print(data_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 全1数组
import numpy as np
data_2 = np.ones(shape=(5,3))
print(data_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
%%python -u
# 全空数组，数据是未初始化的，里面的值可能是随机值
import numpy as np
data_3 = np.empty(shape=(5,3))
print(data_3)

[[6.95263416e-310 2.22523004e-307 2.22523004e-307]
 [1.11258786e-306 1.33511018e-306 1.33511969e-306]
 [6.23037996e-307 1.69121639e-306 1.78022342e-306]
 [8.06635958e-308 1.11261706e-306 1.24610383e-306]
 [1.15710088e-306 2.33423131e-312 1.50192486e-307]]


### 创建有连续序列的数组 arange

`arange([start],stop[,step,],dtype=None)`

In [21]:
import numpy as np
data = np.arange(10,16,2) # 10-16的数据，步长为2
print(data)

[10 12 14]


### 创建有连续间隔的数组 linspace

线性等分向量（linear space），在一个指定区间内按照指定的步长，将区间均等分，生成的是一个线段类型的数组。生成的线性间隔数据中，是有把区间的两端加进去的。

In [22]:
import numpy as np
# 创建线段型数据
data = np.linspace(1,10,20) # 开始端1，结束端10，且分割成20个数据，生成线段
print(data)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 创建随机数组

In [23]:
import numpy as np
data = np.random.rand(3,4)
print(data)

[[0.66750796 0.42178946 0.83589059 0.51427652]
 [0.5893782  0.37600811 0.01677796 0.07676108]
 [0.68359976 0.01104959 0.08454112 0.36892236]]


In [24]:
import numpy as np
data = np.random.randint(2,5,size=(4,5));
print(data)

[[3 3 2 4 3]
 [3 2 4 2 2]
 [2 2 3 4 3]
 [4 2 4 2 3]]


### 改变数组形状

In [28]:
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5]
data = np.array([data1,data2])

print(data)
print("改之前的数组形状为:")
print(data.shape)

data = data.reshape((5,2))
print(data)
print("改之后的数组形状为:")
print(data.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
改之前的数组形状为:
(2, 5)
[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]
改之后的数组形状为:
(5, 2)


### 数组转置

In [29]:
import numpy as np
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
data_array = np.array(data)
print("没有转置数组之前数组为：")
print(data)
print("转置数组之后数组为：")
print(data_array.T)

没有转置数组之前数组为：
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
转置数组之后数组为：
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 数组显示

Numpy 数组的索引遵循 Python 中 `x[obj]` 模式，也就是通过下标来索引对应位置的元素。

In [2]:
import numpy as np
b = np.arange(20).reshape(4,5)
print(b[-1])

[15 16 17 18 19]


### 数组维度 ndim

In [30]:
data = np.array([1,2,3])
print(data.ndim)

1


### 数组形状shape

In [31]:
data = np.array([1,2,3])
print(data.shape)

(3,)


### 数组中元素个数

In [32]:
data = np.array([1,2,3])
print(data.size)

3


### 数组的数据类型 dtype

In [33]:
data = np.array([1,2,3])
print(data.dtype)

int32


## 数组的运算

In [34]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2
print(result)

[5 7 9]


In [35]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result=array1 * array2
print(result)

[ 4 10 18]


In [37]:
# 数组的平均值

import numpy as np
data = [1,5,6,9]
mindle = np.mean(data)
print(mindle)

5.25


In [38]:
# 数组的中位数

import numpy as np
data = [1,5,6,9]
data1 = np.median(data)
print(data1)

5.5


In [39]:
# 一维数组切片

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [48]:
# 多维数组切片



## 数组堆叠

In [50]:
# 垂直堆叠 
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [51]:
# 水平堆叠
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [52]:
# 深度堆叠
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


## 保存和加载数组

In [59]:
# 保存数组到文件

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.save('my_array.npy', data)

In [60]:
# 加载数组

import numpy as np
loaded_data = np.load('my_array.npy')
print(loaded_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
